#pragma once

#include <Windows.h>

constexpr auto PLUGIN_NAME = "IASsure";
constexpr auto PLUGIN_VERSION = "1.1.0";
constexpr auto PLUGIN_AUTHOR = "Nick Mueller";
constexpr auto PLUGIN_LICENSE = "(c) 2022, MIT License";

constexpr auto SETTINGS_DELIMITER = '|';

const int TAG_ITEM_CALCULATED_IAS = 1;
const int TAG_ITEM_CALCULATED_IAS_TOGGLABLE = 2;
const int TAG_ITEM_CALCULATED_MACH = 3;
const int TAG_ITEM_CALCULATED_MACH_TOGGLABLE = 4;

const int TAG_FUNC_OPEN_REPORTED_IAS_MENU = 100;
const int TAG_FUNC_CLEAR_REPORTED_IAS = 101;
const int TAG_FUNC_TOGGLE_CALCULATED_IAS = 102;
const int TAG_FUNC_OPEN_REPORTED_MACH_MENU = 103;
const int TAG_FUNC_CLEAR_REPORTED_MACH = 104;
const int TAG_FUNC_TOGGLE_CALCULATED_MACH = 105;
const int TAG_FUNC_SET_REPORTED_IAS = 200;
const int TAG_FUNC_SET_REPORTED_MACH = 201;

const int MIN_MIN_REPORTED_IAS = 0;
const int MAX_MIN_REPORTED_IAS = 500;
const int MIN_MAX_REPORTED_IAS = 0;
const int MAX_MAX_REPORTED_IAS = 500;
const int MIN_INTERVAL_REPORTED_IAS = 1;
const int MAX_INTERVAL_REPORTED_IAS = 500;
