name: Release

on:
  push:
    tags: [ "v*.*.*" ]

env:
  SOLUTION_FILE_PATH: IASsure.sln

  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x86

permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: windows-latest
    name: "Build and test"

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}

    - name: Test
      uses: microsoft/vstest-action@v1.0.0
      with:
        testAssembly: 'IASsureTest.dll'
        searchFolder: '${{env.BUILD_CONFIGURATION}}/'
    
    - name: Upload plugin DLL artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugin-dll
        path: '${{env.BUILD_CONFIGURATION}}/IASsure.dll'

  publish-test-results:
    runs-on: windows-latest
    name: "Publish Tests Results"
    needs: build-and-test
    
    if: success() || failure()

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      with:
        trx_files: "artifacts/**/*.trx"

  release:
    runs-on: ubuntu-latest
    name: "Release"
    needs: [build-and-test, publish-test-results]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: plugin-dll
    
    - name: Create Archive
      run: zip IASsure_${{env.GITHUB_REF_NAME}}.zip IASsure.dll README.md LICENSE
      
    - name: Create checksums.txt
      run: sha256sum IASsure_${{env.GITHUB_REF_NAME}}.zip > checksums.txt
    
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
    
    - name: Sign checksums.txt
      run: gpg --output checksums.txt.sig --sign checksums.txt

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          IASsure_${{env.GITHUB_REF_NAME}}.zip
          checksums.txt
          checksums.txt.sig
